### ISSUE TITLE
Possible bug with KeepAlive + RPAF_SetHostName On

### ISSUE THREAD

**Issue by abcarroll** [gnif/mod_rpaf#52] opened 2017-09-01 15:37 UTC
$ httpd -v
    Server version: Apache/2.2.32 (Unix)
    Server built:   Jun 21 2017 19:11:57

    $ uname -a
    Linux test-www.mysite.local 4.9.43-17.38.amzn1.x86_64 #1 SMP Thu Aug 17 00:20:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Using mod_rpaf latest stable from git as of today, self-compiled, nothing fancy otherwise.

Quick summary:

Installed mod_rpaf about a week ago.  Created a simple `test.php` file that printed out the remote address to test.  I am running behind Amazon ELBs.   Note that it turns out the access logs were mirroring the same values in the php script -- so it's nothing specific to php.

    LoadModule rpaf_module modules/mod_rpaf.so
    RPAF_Enable             On
    RPAF_ProxyIPs           10.0.0.0/16
    RPAF_SetHostName        On
    RPAF_SetHTTPS           On
    RPAF_SetPort            On
    RPAF_ForbidIfNotProxy   Off

At the time I misunderstood the actual meaning of `RPAF_SetHostName`.  I loaded the page with HTTP + HTTPS and both quick tests showed what I desired -- `REMOTE_ADDR` being set, `HTTPS` being set, etc.

Long story short, after some complaints of things being broken, it turns out that when using this with SSL, (i.e. `X-Forwarded-Proto` + `X-Forwarded-Port` being set by upstream) for some weird reason the remote address was only being set on the first request of keep-alive.

I verified this by turning off Keepalive entirely, and it no longer exhibited the behaviour.  Turning keepalive back on, -- the first request of the keepalive session would have the appropriate values overridden, and subsequent requests would go back to the upstream values.

I turned mod_ssl off entirely (completely removed the LoadModule line) after reading the warning, still same thing.

Luckily, we don't need SetHostName, so turning it to `Off` fixes this behaviour and allows the use of KeepAlive, but it is just strange.  Perhaps something to do with our older version of Apache?   Can provide more details if necessary.

**Comment by AndreiG6** [comment] 2017-09-01 16:04
This is probably a dupe of #42

**Comment by gnif** [comment] 2017-09-02 06:50
Confirmed, this is a duplicate of #42, closing

**Closed as completed by gnif** 2017-09-02 06:50 UTC
